"""Memories -> the instruction files agents already read.

This is the whole delivery story. Every target agent reads a plain instruction
file from the repo, so delivery needs no per-agent integration: a new agent costs
one compile target, not a plugin.

Output must be byte-stable for a given input, because it is a committed generated
artifact and CI diffs it.
"""
from __future__ import annotations

import fnmatch
import pathlib

TIER_ORDER = {"always": 0, "scoped": 1, "on_demand": 2, "pre_action": 3}

BANNER = ("<!-- GENERATED by jedimem. Do not edit inside these markers; edit\n"
          "     .jedimem/memories/*.md and run `jedimem compile`. Content outside\n"
          "     the markers is yours and always wins. -->")


def _sort(mems):
    # Deterministic and content-derived. Never mtime.
    return sorted(mems, key=lambda m: (TIER_ORDER.get(m.tier, 9), m.kind, m.id))


def render(memories, always_chars=6000, scoped_chars=4000, marker_begin="",
           marker_end="") -> str:
    mems = _sort([m for m in memories if m.status == "active"])
    lines = [marker_begin, BANNER, ""]

    always = [m for m in mems if m.tier == "always"]
    demoted = []
    used = 0
    if always:
        lines.append("## Always")
        for m in always:
            entry = f"- **[{m.kind}]** {m.headline}"
            if m.scope not in ("**", ""):
                entry += f"  _(scope: `{m.scope}`)_"
            if used + len(entry) > always_chars:
                demoted.append(m)
                continue
            lines.append(entry)
            used += len(entry) + 1
        lines.append("")

    scoped = [m for m in mems if m.tier == "scoped"]
    if scoped:
        by_scope = {}
        for m in scoped:
            by_scope.setdefault(m.scope, []).append(m)
        lines.append("## When touching matching files")
        for scope in sorted(by_scope):
            lines.append(f"\n`{scope}`:")
            budget = 0
            for m in by_scope[scope]:
                entry = f"- **[{m.kind}]** {m.headline}"
                if budget + len(entry) > scoped_chars:
                    demoted.append(m)
                    continue
                lines.append(entry)
                budget += len(entry) + 1
        lines.append("")

    on_demand = [m for m in mems if m.tier in ("on_demand", "pre_action")]
    if on_demand:
        lines.append("## Available on request")
        lines.append("Ask for these by name, or read the file. "
                     "They are not loaded by default to keep this file small.")
        for m in on_demand:
            lines.append(f"- **[{m.kind}]** {m.headline.split('.')[0]}. "
                         f"→ `.jedimem/memories/{m.id}.md`")
        lines.append("")

    if demoted:
        # Never truncate silently. Codex truncates AGENTS.md at
        # project_doc_max_bytes without telling anyone; we say so instead.
        lines.append(f"<!-- {len(demoted)} memory(ies) exceeded the budget and were")
        lines.append("     demoted to on-request. Run `jedimem status` to see which. -->")
        lines.append("")

    lines.append(marker_end)
    return "\n".join(lines).rstrip() + "\n"


def splice(existing: str, section: str, begin: str, end: str) -> str:
    """Replace the delimited section, leaving everything else byte-identical.

    Must be idempotent: splice(splice(x)) == splice(x). The subtle case is a
    file that contains ONLY the generated section (we created it), where a
    naive prefix join adds leading blank lines on every run and CI reports the
    file as perpetually stale.
    """
    if begin in existing and end in existing:
        pre = existing.split(begin)[0]
        post = existing.split(end, 1)[1]
        head = pre.rstrip("\n") + "\n\n" if pre.strip() else ""
        tail = post.lstrip("\n")
        return head + section + ("\n" + tail if tail else "")
    if not existing.strip():
        return section
    return existing.rstrip("\n") + "\n\n" + section


def compile_repo(root: pathlib.Path, memories, cfg, check=False):
    """Returns (changed_targets, demoted_count)."""
    section = render(memories,
                     always_chars=int(cfg.get("always_chars", 6000)),
                     scoped_chars=int(cfg.get("scoped_chars_per_glob", 4000)),
                     marker_begin=cfg["marker_begin"], marker_end=cfg["marker_end"])
    changed = []
    for name in cfg.targets:
        p = pathlib.Path(root) / name
        cur = p.read_text(encoding="utf-8") if p.exists() else ""
        new = splice(cur, section, cfg["marker_begin"], cfg["marker_end"])
        if cur != new:
            changed.append(name)
            if not check:
                p.write_text(new, encoding="utf-8")
    return changed


def scope_matches(scope: str, path: str) -> bool:
    if scope in ("**", ""):
        return True
    return fnmatch.fnmatch(path, scope) or fnmatch.fnmatch(path, scope.rstrip("/*") + "/*")
