//! Memories -> the instruction files agents already read.
//!
//! This is the whole delivery story. Every target agent reads a plain
//! instruction file from the repo, so delivery needs no per-agent integration:
//! a new agent costs one compile target, not a plugin.
//!
//! Output must be byte-stable for a given input, because it is a committed
//! generated artifact and CI diffs it.

use crate::memory::Memory;
use std::collections::BTreeMap;
use std::path::Path;

pub const BANNER: &str = "<!-- GENERATED by jedimem. Do not edit inside these markers; edit\n     .jedimem/memories/*.md and run `jedimem compile`. Content outside\n     the markers is yours and always wins. -->";

fn tier_order(t: &str) -> u8 {
    match t {
        "always" => 0,
        "scoped" => 1,
        "on_demand" => 2,
        "pre_action" => 3,
        _ => 9,
    }
}

pub struct RenderOpts<'a> {
    pub always_chars: usize,
    pub scoped_chars: usize,
    pub marker_begin: &'a str,
    pub marker_end: &'a str,
}

pub fn render(memories: &[Memory], o: &RenderOpts) -> String {
    let mut mems: Vec<&Memory> = memories.iter().filter(|m| m.status == "active").collect();
    // Deterministic and content-derived. Never mtime.
    mems.sort_by(|a, b| {
        tier_order(&a.tier)
            .cmp(&tier_order(&b.tier))
            .then(a.kind.cmp(&b.kind))
            .then(a.id.cmp(&b.id))
    });

    let mut lines: Vec<String> = vec![
        o.marker_begin.to_string(),
        BANNER.to_string(),
        String::new(),
    ];
    let mut demoted = 0usize;

    let always: Vec<&&Memory> = mems.iter().filter(|m| m.tier == "always").collect();
    if !always.is_empty() {
        lines.push("## Always".into());
        let mut used = 0usize;
        for m in &always {
            let mut entry = format!("- **[{}]** {}", m.kind, m.headline());
            if m.scope != "**" && !m.scope.is_empty() {
                entry.push_str(&format!("  _(scope: `{}`)_", m.scope));
            }
            if used + entry.len() > o.always_chars {
                demoted += 1;
                continue;
            }
            used += entry.len() + 1;
            lines.push(entry);
        }
        lines.push(String::new());
    }

    let scoped: Vec<&&Memory> = mems.iter().filter(|m| m.tier == "scoped").collect();
    if !scoped.is_empty() {
        let mut by_scope: BTreeMap<&str, Vec<&&Memory>> = BTreeMap::new();
        for m in &scoped {
            by_scope.entry(m.scope.as_str()).or_default().push(m);
        }
        lines.push("## When touching matching files".into());
        for (scope, group) in by_scope {
            lines.push(String::new());
            lines.push(format!("`{}`:", scope));
            let mut budget = 0usize;
            for m in group {
                let entry = format!("- **[{}]** {}", m.kind, m.headline());
                if budget + entry.len() > o.scoped_chars {
                    demoted += 1;
                    continue;
                }
                budget += entry.len() + 1;
                lines.push(entry);
            }
        }
        lines.push(String::new());
    }

    let on_demand: Vec<&&Memory> = mems
        .iter()
        .filter(|m| m.tier == "on_demand" || m.tier == "pre_action")
        .collect();
    if !on_demand.is_empty() {
        lines.push("## Available on request".into());
        lines.push(
            "Ask for these by name, or read the file. They are not loaded by default \
             to keep this file small."
                .into(),
        );
        for m in on_demand {
            let head = m.headline();
            let first = head.split('.').next().unwrap_or(&head);
            lines.push(format!(
                "- **[{}]** {}. → `.jedimem/memories/{}.md`",
                m.kind, first, m.id
            ));
        }
        lines.push(String::new());
    }

    if demoted > 0 {
        // Never truncate silently. Codex truncates AGENTS.md at
        // project_doc_max_bytes without telling anyone; we say so instead.
        lines.push(format!(
            "<!-- {} memory(ies) exceeded the budget and were",
            demoted
        ));
        lines.push("     demoted to on-request. Run `jedimem status` to see which. -->".into());
        lines.push(String::new());
    }

    lines.push(o.marker_end.to_string());
    let joined = lines.join("\n");
    format!("{}\n", joined.trim_end())
}

/// Replace the delimited section, leaving everything else byte-identical.
///
/// Must be idempotent: splice(splice(x)) == splice(x). The subtle case is a
/// file containing ONLY the generated section (we created it), where a naive
/// prefix join adds leading blank lines on every run and CI then reports the
/// file as perpetually stale.
pub fn splice(existing: &str, section: &str, begin: &str, end: &str) -> String {
    if existing.contains(begin) && existing.contains(end) {
        let pre = existing.split(begin).next().unwrap_or("");
        let post = existing.split_once(end).map(|x| x.1).unwrap_or("");
        let head = if pre.trim().is_empty() {
            String::new()
        } else {
            format!("{}\n\n", pre.trim_end_matches('\n'))
        };
        let tail = post.trim_start_matches('\n');
        return if tail.is_empty() {
            format!("{}{}", head, section)
        } else {
            format!("{}{}\n{}", head, section, tail)
        };
    }
    if existing.trim().is_empty() {
        return section.to_string();
    }
    format!("{}\n\n{}", existing.trim_end_matches('\n'), section)
}

/// Returns the list of targets that changed (or would change, when `check`).
pub fn compile_repo(
    root: &Path,
    memories: &[Memory],
    cfg: &crate::config::Config,
    check: bool,
) -> std::io::Result<Vec<String>> {
    let section = render(
        memories,
        &RenderOpts {
            always_chars: cfg.num("always_chars", 6000),
            scoped_chars: cfg.num("scoped_chars_per_glob", 4000),
            marker_begin: cfg.get("marker_begin"),
            marker_end: cfg.get("marker_end"),
        },
    );
    let mut changed = Vec::new();
    for name in cfg.targets() {
        let p = root.join(&name);
        let cur = std::fs::read_to_string(&p).unwrap_or_default();
        let new = splice(
            &cur,
            &section,
            cfg.get("marker_begin"),
            cfg.get("marker_end"),
        );
        if cur != new {
            changed.push(name.clone());
            if !check {
                std::fs::write(&p, new)?;
            }
        }
    }
    Ok(changed)
}
